name: Java CI with Maven

on:
  push:
   branches:
    - main

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy 
      # run: sudo kill -9 'sudo lsof -t -i:8080' & java -jar target/demo-1.0.0-SNAPSHOT.jar &
      run: |
          java -jar target/*.jar & 
          sleep 180
          kill %1
    

